CREATE USER 'biblioteka'@'localhost' IDENTIFIED BY 'V!OSvw^4QMY:Q4F+G';
CREATE DATABASE IF NOT EXISTS biblioteka DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
GRANT ALL PRIVILEGES ON biblioteka.* TO 'biblioteka'@'localhost';
USE biblioteka;

CREATE TABLE IF NOT EXISTS uzytkownik (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	pesel VARCHAR(11) NOT NULL,
	haslo VARCHAR(255) NOT NULL,
	imie VARCHAR(32) NOT NULL,
	nazwisko VARCHAR(32) NOT NULL,
	miasto VARCHAR(32) NOT NULL,
	ulica VARCHAR(32) NOT NULL,
	nr_domu VARCHAR(10) NOT NULL,
	kod_pocztowy VARCHAR(5) NOT NULL,
	uprawnienia TINYINT(1) UNSIGNED NOT NULL DEFAULT '0'
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS ksiazka (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	numer_isbn VARCHAR(32) NOT NULL,
	tytul VARCHAR(128) NOT NULL,
	autor VARCHAR(64) NOT NULL,
	rok_wydania VARCHAR(4) NOT NULL,
	wydawnictwo VARCHAR(64) NOT NULL,
	opis VARCHAR(512)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS rezerwacja (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	id_rezerwujacego INT UNSIGNED NOT NULL,
	id_ksiazki INT UNSIGNED NOT NULL,
	status_rezerwacji TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
	opis VARCHAR(512),
	FOREIGN KEY (id_rezerwujacego) REFERENCES uzytkownik(id),
	FOREIGN KEY (id_ksiazki) REFERENCES ksiazka(id)
) ENGINE=InnoDB;

